# Generated by Django 2.2.3 on 2019-07-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
